### ISSUE TITLE
Unique Factory not selling products

### ISSUE THREAD

**Issue by 3r1u5** [algernon-A/TransferController#16]
I've been trying out Transfer Controller for the last few days and its been fine, though I think this last update(0.3) may have introduced a bug that stops unique factories from being able to sell their products. I have tested with and with out restrictions both building and district, I tested with specific districts and adding all districts, I tried only allowing warehouses both vanilla and custom, I also tried turning the export on and off but nothing worked, I used move it to reset the factory and allow it to find buyers again but as soon as it fills up on unique products it immediately says not enough buyers, yet it still receives shipments from other industries dlc buildings.

**Comment by algernon-A** [comment]
Unable to reproduce (in fact, quite the opposite).

Do you have any hard data or systemic evidence that would suggest an issue with the mod?

**Comment by 3r1u5** [comment]
it might have been a conflict with another mod i had, also had better luck starting a new city. great work!
