### ISSUE TITLE
New distance-based matching algorithm off leads to export issues.

### ISSUE THREAD

**Issue by DaEgi01** [algernon-A/TransferController#21]
I am using this mod with "use new distance-based matching algorithm" turned off.
My large grain silos are full, storage mode set to balanced, Goods out - Allow exports is set to on, without any further restrictions.
Truck usage stays on 0/25 though, my expectation here is that the goods are exported until the storage reaches ~50%.
Turning "New distance-based matching algorithm" instantly leads to trucks starting to export the grain.

**Comment by algernon-A** [comment]
Yes, there appear to be some issues with the legacy game-based algorithm, and I'm going to remove it in an upcoming update.  I don't think it's worth investing the effort given the much better outcomes the new algorithm provides.

**Comment by algernon-A** [comment]
Removed legacy algorithm in 0.7.4.
