### ISSUE TITLE
No reflection in per frame methods.

### ISSUE THREAD

**Issue by DaEgi01** [algernon-A/TransferController#5]
You should remove reflection from per frame methods like MatchOffer.
Performance will tank otherwise!
Try https://harmony.pardeike.net/api/HarmonyLib.AccessTools.FieldRef-2.html instead :)
This creates either refs or deleteges in order to get and set fields or methods instead of reflection.
This is still somewhat slower than direct field access but like 10x faster than reflection.

**Comment by algernon-A** [comment]
The reflection is only there for 0.1 to keep things simple and make sure everything is working before implementing the transpiler in 0.2 (even faster than refs/delegates!)

**Comment by algernon-A** [comment]
BTW, the medium-term approach is to use separate threads.

**Comment by algernon-A** [comment]
Initial placeholder transpiler implemented in 84796459c27b316e84ebcf878c0f557be7e70137
